name: PyBinding

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/executable.yml

jobs:
  build:
    strategy:
      matrix:
        arch: [ x86-64, x86-64-v2, x86-64-v3, x86-64-v4, apple-m1, apple-m2, apple-m3, apple-m4 ]
        os: [ ubuntu-latest , windows-latest, macos-latest ]
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
        exclude:
          - os: windows-latest
            arch: apple-m1
          - os: windows-latest
            arch: apple-m2
          - os: windows-latest
            arch: apple-m3
          - os: windows-latest
            arch: apple-m4
          - os: ubuntu-latest
            arch: apple-m1
          - os: ubuntu-latest
            arch: apple-m2
          - os: ubuntu-latest
            arch: apple-m3
          - os: ubuntu-latest
            arch: apple-m4
          - os: macos-latest
            arch: x86-64
          - os: macos-latest
            arch: x86-64-v2
          - os: macos-latest
            arch: x86-64-v3
          - os: macos-latest
            arch: x86-64-v4

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - if: matrix.os == 'ubuntu-latest'
        name: Install Linux Dependencies
        run: |
          sudo apt install ninja-build
          sudo apt remove python3-lldb-14
      - if: matrix.os == 'windows-latest'
        name: Install Windows Dependencies
        run: |
          choco install ninja

      - if: matrix.os == 'ubuntu-latest'
        name: Install Clang 20 (Ubuntu)
        run: |
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo rm -rf llvm.sh
      - if: matrix.os == 'windows-latest'
        name: Install Clang 20 (Windows)
        run: |
          choco install llvm --version 20.1.0 -y
      - if: matrix.os == 'macos-latest'
        name: Install Clang 19 (MacOS)
        run: |
          brew install llvm@19

      - if: matrix.os == 'ubuntu-latest'
        name: Set CC and CXX for Linux
        run: |
          echo "CC=clang-20" >> $GITHUB_ENV
          echo "CXX=clang++-20" >> $GITHUB_ENV
      - if: matrix.os == 'windows-latest'
        name: Set CC and CXX for Windows
        shell: powershell
        run: |
          echo "CC=clang" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - if: matrix.os == 'macos-latest'
        name: Set CC and CXX for MacOS
        run: |
          echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
          echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV
          echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_ENV


      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scikit-build-core build twine pybind11 setuptools build tomlkit

      - name: CMake Arguments (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "CMAKE_CXX_FLAGS=-mcpu=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: CMake Arguments (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "CMAKE_CXX_FLAGS=-march=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: CMake Arguments (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "CMAKE_CXX_FLAGS=-march=${{ matrix.arch }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set architecture environment variable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "ARCHITECTURE=${{ matrix.arch }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set architecture environment variable (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        run: |
          echo "ARCHITECTURE=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Extract C++ Standard Library Version (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "Detecting STL version using $env:CXX"
          
          $cxx_version = & $env:CXX -dM -E -x c++ NUL 2>$null | Select-String '_MSC_VER' | ForEach-Object {
            if ($_ -match '_MSC_VER\s+(\d+)') {
              "msvc$($matches[1])"
            }
          }
          
          echo "CXX_VERSION=$cxx_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Extract C++ Standard Library Version (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          echo "Detecting STL version on ${{ matrix.os }}"
          
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            glibc_version=$(getconf GNU_LIBC_VERSION | awk '{print $2}')
            STL_VERSION="libstdcxx${glibc_version}"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            clang_version=$(clang++ --version | grep -i 'clang version' | awk '{print $4}')
            STL_VERSION="libcxx${clang_version}"
          else
            STL_VERSION="unknown"
          fi
          
          echo "Detected STL version: $STL_VERSION"
          echo "CXX_VERSION=$STL_VERSION" >> $GITHUB_ENV
          
      - name: Define version
        shell: python
        run: |
          import os
          import tomlkit
  
          architecture = os.environ.get("ARCHITECTURE", "").replace("-", "_")
          cxx_version  = os.environ.get("CXX_VERSION", "")
          
          with open("pyproject.toml", "r", encoding="utf-8") as f:
            doc = tomlkit.parse(f.read())
          
          doc["project"]["version"] = f"{doc['project']['version']}.arch.{architecture}.{cxx_version}"
          
          with open("pyproject.toml", "w", encoding="utf-8") as f:
            f.write(tomlkit.dumps(doc))
          
          print(f"Set project version to {doc['project']['version']}")

      - name: Build Wheel
        run: |
          python -m build

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: StockDory-python.${{ matrix.python }}-${{ matrix.os }}-${{ matrix.arch }}.whl
          path: ./dist/*.whl

  publish:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Python Packages Repository
      url: https://pypi.fury.io/theblackplague/stockdory

    steps:
      - name: Download Wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Python Dependencies
        run: |
          python -m pip install --upgrade twine

      - name: Show downloaded Wheels
        run: ls -R dist

      - name: Publish Wheels (Gemfury)
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          python -m twine upload \
          --repository-url https://pypi.fury.io/theblackplague/ \
          -u theblackplague \
          -p "${FURY_TOKEN}" \
          --non-interactive \
          --skip-existing \
          dist/*
